repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude_types: [css, markdown, text, svg]
      - id: trailing-whitespace
        exclude_types: [html, markdown, text]
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        entry: flake8 --ignore=E203,W503 --max-line-length=122
  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        entry: codespell
        args: [ '--ignore-words-list=ba,buil,coo,ether,hist,hsi,mape,navagation,operatio,pres,ser,yeld', '--quiet-level=2', '--skip=./tests,.git,*.css,*.csv,*.html,*.ini,*.ipynb,*.js,*.json,*.lock,*.scss,*.txt,*.yaml' ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910-1'
    hooks:
      - id: mypy
        args: [ '--no-strict-optional', '--ignore-missing-imports', '--exclude=/setup\.py$', '.']
  - repo: local
    hooks:
       - id: pylint
         name: pylint
         entry: pylint discordbot gamestonk_terminal terminal.py tests
         language: system
         types: [python]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: [ '--baseline', '.secrets.baseline', '--exclude-files', 'tests/cassettes/*' ]
        exclude: package.lock.json
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args: [ --py36-plus ]
