# https://python-poetry.org/docs/dependency-specification/
[tool.poetry]
name = "GamestonkTerminal"
version = "0.1.0"
description = ""
authors = ["Didier Rodrigues Lopes"]
packages = [
    { include = "gamestonk_terminal" },
]

[tool.poetry.scripts]
gst = 'terminal:terminal'

[tool.poetry.dependencies]
python = "^3.8,<3.10"
iso8601 = "^0.1.14"
FundamentalAnalysis = "^0.2.6"
requests = "^2.25.1"
alpha-vantage = "^2.3.1"
finviz = "^1.3.4"
bs4 = "^0.0.1"
rapidfuzz = "^1.1.1"
yfinance = "^0.1.63"
prettytable = "^2.0.0"
psaw = "^0.0.12"
praw = "^7.1.4"
Quandl = "^3.6.0"
pytrends = "^4.7.3"
matplotlib = "^3.3.3"
plotly = "^4.14.3"
colorama = "^0.4.4"
papermill = "^2.3.2"
prompt-toolkit = "^3.0.16"
jupyter = "^1.0.0"
jupyterlab = "^3.2.4"
mplfinance = "^0.12.7-alpha.7"
seaborn = "^0.11.0"
fredapi = "^0.4.3"
screeninfo = "^0.6.7"
robin-stocks = "^2.0.3"
termcolor = "^1.1.0"
pyally = "^1.1.2"
pycoingecko = "^1.4.0"
detecta = "^0.0.5"
tradingview-ta = "^3.2.3"
finvizfinance = "^0.9.3"
Pillow = "^8.2.0"
statsmodels = "^0.12.2"
tabulate = "^0.8.9"
pyportfolioopt = "^1.4.1"
selenium = "^3.141.0"
python-coinmarketcap = "^0.2"
oandapyV20 = "^0.6.3"
valinvest = "^0.0.2"
bt = "^0.2.9"
vaderSentiment = "3.3.2"
mypy = "^0.901"
GitPython = "^3.1.17"
fear-greed-index = "^0.1.3"
pyEX = "^0.5.0"
sentiment-investor = "^2.0.0"
fred = "^3.1"
financedatabase = "1.0.2"
reportlab = "^3.6.2"
holidays = "^0.11.3"
degiro-connector = "^2.0.3"
python-binance = "^1.0.15"
thepassiveinvestor = "^1.0.10"
pymongo = "3.11"
tensorflow = {version = "^2.7.0", optional = true}
pandas-ta = "^0.3.14-beta.0"
pmdarima = "^1.8.4"
pyrsistent = "^0.18.0"
openpyxl = "^3.0.9"
jsonschema = "3.2.0"
pandas = "^1.3.4"
discord = {version = "^1.7.3", optional = true}
discord-components = {version = "^2.1.2", optional = true}
pyimgur = {version = "^0.6.0", optional = true}
python-dotenv = {version = "^0.19.2", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pylint = "^2.7.2"
flake8 = "^3.9.0"
mypy = "^0.901"
mock = "^4.0.3"
codespell = "^2.0.0"
pyupgrade = "^2.11.0"
sphinx = "4.1.1"
myst-parser = "^0.15.2"
black = "21.7b0"
bandit = "^1.7.0"
coverage = ">=5.5"
vcrpy = "^4.1.1"
pytest-mock = "^3.6.1"
pytest-recording = "^0.12.0"
types-pytz = "^2021.3.1"
types-requests = "^2.26.0"
types-termcolor = "^1.1.2"
types-tabulate = "^0.8.3"
types-PyYAML = "^6.0.1"
types-python-dateutil = "^2.8.3"
pre-commit = "^2.16.0"

[tool.poetry.extras]
prediction = ["tensorflow"]
discord = ["discord", "discord_components", "pyimgur", "python-dotenv"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Notes for developers:
# 1. numpy >= 1.20.0 sometimes has issues with tensorflow=2.4.1
# 2. The following packages dropped support for python<3.7:
#    pandas >= 1.2.0
#    numpy >= 1.20.0
#    scipy >= 1.6.0
# 3. The following often cause poetry to misbehave:
#    pyrsistent >= 0.17
#    regex >= 2021
